version: "2"
services:
  percona-server:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306"
    volumes:
      # create volumes for use
      - /var/lib/mysql
